import Home from './Home';
import Hot from './Hot';
import Search from './Search';
import History from './History';
import Follow from './Follow';
import Category from './Category';
import Logins from './Logins';
import Register from './Register';
import Men from './Men';
import Women from './Women';
import ReadStory from './ReadStory';
import Details from './Details';
import ForgetPassword from './ForgetPassword';
import DashBoard from './DashBoard';
export { Home, Hot, Search, History, Follow, Logins, Register, Category, Men, Women, ReadStory, Details, ForgetPassword, DashBoard };
