import Header from './Header';
import FormLogin from './FormLogin';
import FormSearch from './FormSearch';
import Nav from './Nav';
import NavItem from './NavItem';
import Sliders from './Sliders';
import Card from './Card';
import Sidebar from './Sidebar';
import CommonTitleSidebar from './CommonTitleSidebar';
import Ranks from './Ranks';
import Footer from './Footer';
import Comments from './Comments';
import BackToTop from './BackToTop';
export { Header, Nav, FormLogin, FormSearch, Sliders, NavItem, Card, Sidebar, CommonTitleSidebar, Ranks, Footer, Comments, BackToTop };
